#!/bin/bash

. pn_lib

# build classes
$PN/pn/gradlew -p=$PN/pn build

# build the client lib
$PN/pn/gradlew -p=$PN/pn buildclient

if [ $? -ne 0 ]; then
   exit
fi

# For now we will just run on localhost and pass in all arguments
# In the future when this script must process exclusive arguments, change the index on "${@:i}" to prevent passing them
# to the program
java -Dfile.encoding=UTF-8 -javaagent:"$PN/ea-async-lib/ea-async-1.2.1.jar" -cp "$PN/pn/build/libs/client.jar" com.medleystudios.pn.client.PNClient "${@:1}"
