#!/bin/bash

. pn_lib

chmod 400 ${privateKeyPath}

src=$1
serverIdentifier=$2
dst=$3

if [ -z "$src" ] || [ -z "$serverIdentifier" ] || [ -z "$dst" ]
then
   echo "Expected 3 arguments: src, serverIdentifier, and dst!"
else
   server=`get_server $serverIdentifier`

   if [ -z "$server" ]
   then
      echo "Could not find a server with the identifier '${serverIdentifier}' in ${libDir}/servers.txt!"
   else
      serverName=`get_server_name $server`
      serverSshIp=`get_server_ssh_ip $server`
         
      if [ -z "$serverName" ] || [ -z "$serverSshIp" ]
      then
         echo "Server data syntax error '$server' in ${libDir}/servers.txt!"
      else
         echo "SCP src:$src -r dst:ubuntu@$serverSshIp:$dst [${serverName}]"
         scp -oStrictHostKeyChecking=no -i ${privateKeyPath} -r $src ubuntu@$serverSshIp:$dst
      fi
   fi
fi
